### PR TITLE
geopackage of three shapefiles

### PR DESCRIPTION
**Pull request by brentfraser**
For editing enhancement

### CODE REVIEW

**Comment by theduckylittle** [comment]
Can we add an "ORIGINS.md" file that describes/links-to the origin of the source data and potentially slap in a copy of the TIGER data license? I'd just like to make sure that when we inventory data we can trace it back.

**Comment by brentfraser** [comment]
will do.

**Comment by brentfraser** [comment]
Do you have  link to the TIGER data license?

**Comment by klassenjs** [comment]
```
ogr2ogr -f GPKG -clipsrc -93.28 44.47 -93.04 44.64 census-clip.gpkg census.gpkg
```

Clips it to approximately the parcel dataset extent and reduces it down to 184K.  That might be too tight to have enough interesting features though.

image

**Comment by brentfraser** [comment]
@klassenjs I'll do a "spat" instead of a "clipsrc" and widen the extents a little.  It makes a gpkg about 500KB.  Much better than the 15 MB.  Thanks!

**Comment by theduckylittle** [comment]
I actually *LOVE* this PR:

1. Instructions on how to recreate
2. Useful OGR commands for people looking around for a quicky-guide.
3. Great demo data from an awesome open-data provider like the Census.

Thanks everyone!

**Pull request merged**
