### PR TITLE
add imagetype, for testing mapfiles

### PR DESCRIPTION
**Pull request by jmckenna**
- for years I have to add this manually so I can test the demo mapfiles (otherwise map2img/shp2img reports hard error of `msPrepareImage(): Image handling error. Unable to initialize image.`
- I believe adding this png OUTPUTFORMAT does not impact the demo in any way (please confirm/correct me if so)

### CODE REVIEW

**Comment by klassenjs** [comment]
Something odd is going on here.

`map2img -m basemap.map -o out.png` gives me that error but

`map2img -m basemap.map -i PNG -o out.png` works fine (without this patch).

Digging further:

`mapoutput.c` from MapServer states: 

> "If IMAGETYPE not set use the first user defined OUTPUTFORMAT."  

We don't set IMAGETYPE in any of our mapfiles, but we do define a GeoJSON output format in `geomoose_globals.map`.  So `map2img` is probably trying to output an image of type GeoJSON and failing.

I think it might be better to set IMAGETYPE in `geomoose_globals.map` than override the PNG OUTPUTFORMAT.

Thoughts?

**Comment by jmckenna** [comment]
I always set IMAGETYPE, I was not sure why GeoMoose chose not to set this.   I'm +1 for IMAGETYPE instead.

**Comment by klassenjs** [comment]
I doubt GeoMoose made a conscious choice to not set it.  It was more likely that it worked for GeoMoose without setting it so nobody noticed.

**Comment by jmckenna** [comment]
Ok, I'll update this pull request...

**Comment by jmckenna** [comment]
done. read to merge.

**Pull request merged**
